# Generated by Django 4.2 on 2023-06-08 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='task',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='usertenant',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='usertenant',
            name='longitude',
        ),
    ]
