# Generated by Django 4.2 on 2023-06-10 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_task_latitude_task_longitude_usertenant_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='task',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='usertenant',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='usertenant',
            name='longitude',
        ),
    ]
